### ISSUE TITLE
FTP Corrupted

### ISSUE THREAD

**Issue by fpieressa** [tabernarious/f5-automated-backup-iapp#15]
Hi, we have tested in several F5 that backups are corrupted after being sent by FTP by f5-automated-backup-iapp 3.1.4.  It's like the FTP transfer is done before the archiving ends.  Can you please check it?

Thanks!

**Comment by tabernarious** [comment]
I'll take a look as soon as I can. Are the files you receive smaller than if you generate them manually on the F5?

**Comment by fpieressa** [comment]
Hi! Yes, it's like the file transfer starts before the archive ends... thanks!


Enviado desde mi smartphone Samsung Galaxy.
-------- Mensaje original --------De: Daniel Tavernier <notifications@github.com> Fecha: 28/8/18  16:39  (GMT-03:00) Para: tabernarious/f5-automated-backup-iapp <f5-automated-backup-iapp@noreply.github.com> Cc: fpieressa <fpieressa@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [tabernarious/f5-automated-backup-iapp] FTP Corrupted (#15) 
I'll take a look as soon as I can. Are the files you receive smaller than if you generate them manually on the F5?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tabernarious/f5-automated-backup-iapp","title":"tabernarious/f5-automated-backup-iapp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/tabernarious/f5-automated-backup-iapp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tabernarious in #15: I'll take a look as soon as I can. Are the files you receive smaller than if you generate them manually on the F5?"}],"action":{"name":"View Issue","url":"https://github.com/tabernarious/f5-automated-backup-iapp/issues/15#issuecomment-416714387"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tabernarious/f5-automated-backup-iapp/issues/15#issuecomment-416714387",
"url": "https://github.com/tabernarious/f5-automated-backup-iapp/issues/15#issuecomment-416714387",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [tabernarious/f5-automated-backup-iapp] FTP Corrupted (#15)",
"sections": [
{
"text": "",
"activityTitle": "**Daniel Tavernier**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@tabernarious",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"tabernarious/f5-automated-backup-iapp\",\n\"issueId\": 15,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"tabernarious/f5-automated-backup-iapp\",\n\"issueId\": 15\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/tabernarious/f5-automated-backup-iapp/issues/15#issuecomment-416714387"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 365547139\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by tabernarious** [comment]
@fpieressa Unfortunately I cannot replicate your issue. Is it possible that you have a firewall or IPS type device blocking or corrupting the connections? What happens if you manually FTP from the F5 CLI to the server using `ftp`?

**Comment by tabernarious** [comment]
No recent response. This can be reopened if needed.
