### ISSUE TITLE
cannot modify passphrase

### ISSUE THREAD

**Issue by gedeon007** [tabernarious/f5-automated-backup-iapp#16]
Hi,

This iApp is really cool, thank you for your hard work!

I cannot modify the passphrase configured for the UCS using the reconfigure (I get an error message that does not describe what is the problem). Also deleting the Application Service and trying to recreate it with the new password generates the same error.

The problem only exists if I try to use backup schedule frequency. If it is set to disabled, I can modify the passphrase. But if I try to modify the frequency after successful passphrase modification, I get the same error again.

Also tried to delete all application services using this template, even I deleted the template, and the same error occurs when I recreate the whole stuff.

Using template version 3.1.4 and TMOS version 13.1.0.8 (Build 0.0.3).

**Comment by gedeon007** [comment]
OK, so now I found the issue. There was a special character ( [ ) in the passphrase that I wanted to change for. That caused the problem. Having @, #, - and % characters does not cause the issue, only that [ character...

**Comment by tabernarious** [comment]
Excellent sleuthing! I've been meaning to put together a list of known-okay
special characters (or developing a special-character-escaping function).

**Comment by tabernarious** [comment]
@gedeon007, v3.1.7 now supports most special characters. Check it out if you're interested.
