### ISSUE TITLE
CIFS /SMB upload don't work with Server 2018

### ISSUE THREAD

**Issue by tamoorlatif** [tabernarious/f5-automated-backup-iapp#17]
I have been trying to get CIFS/SMB to work with Server 2012 however, keep getting mount failure. Packet capture show F5 v12.1 is trying to negotiate with SMBv1 which Server 2012 does not support and resets the connection. Network share on Server 2012 is works from every other device as long as you are using SMBv2.

**Comment by tamoorlatif** [comment]
I am using iApp v3.1.4 and Windows server is 2012 and 2008. SMB doesn't work with either server.
I tested it in AWS lab using F5 v14 VM with Server 2016 VM and CIFS/SMB seems to work.

**Comment by tabernarious** [comment]
@tamoorlatif, Unfortunately I cannot replicate what you're seeing. I am able to upload via SMB to Windows Server 2012 from v11.6.3, v12.1.3, and v13.1.1.

I did run into an issue during testing with special characters in passwords. I would recommend trying some different/basic passwords to see if that might be your issue. Please report back if you are able to get anything working.

Also, I have now released v3.1.6 with a number of fixes, though none specific to this issue.

**Comment by tabernarious** [comment]
@tamoorlatif, I just released v3.1.7 which adds support for special characters in passwords for SMB/CIFS and FTP. This may help with your issue.

I am looking back at your original note which highlights SMBv1 and SMBv2. I will look into that to see what I can come up with.

**Comment by tamoorlatif** [comment]
@Daniel, In regards to SMB issue, I tested it again in AWS lab with a LTM v14 VM and Server 2012 VM and I was not able to re-create SMB issue. This makes me believe newer versions of F5, specifically v14 is using SMBv2 as compared to v12.1 which tries to negotiate SMBv1. 

Due to difficulties with SMB, I have switched to SCP method and it's working flawlessly. Thank You for looking into it.
