### ISSUE TITLE
Script failing (last version) - can't read "password" : no such variable

### ISSUE THREAD

**Issue by matantal1** [tabernarious/f5-automated-backup-iapp#19]
Script (/Common/f5.automated_backup__iApp-Daily-Backup) generated this Tcl error:
script did not successfully complete: (can't read "password": no such variable
    while executing
"exec echo -e "\#\!/bin/sh\nf5masterkey=\$(f5mku -K)\nusername=\$(echo \"**ommited**" | openssl aes-256-ecb -salt -a ..." line:26)

i"m getting this error tried to change password for archive but still the same.

**Comment by tabernarious** [comment]
@matantal1, which version of this iApp are you running? Which remote method are you using? What special characters does your password have, if any? Did you change anything else?

**Comment by matantal1** [comment]
@tabernarious I used "!" as special character for the account logged but i also tried to removed it and it also fails .
version 3.1.8. Using SMB as the uploading protocol .

**Comment by tabernarious** [comment]
And what version of TMOS are you running? Did you post the whole error above?

**Comment by matantal1** [comment]
13.1.1 build 0.0.4 Final.
Yes i was just tailing /var/tmp/scriptd.out

The earlier lines just show that the configuration was saved locally .
"Saving active configuration...
/var/local/ucs/**omitted**.ucs is saved."

**Comment by tabernarious** [comment]
Unfortunately I cannot replicate what you are seeing. Did the script work previously and broke after you changed something, or is this the first time you're setting it up?

**Comment by matantal1** [comment]
This is the first time..
Would you recommend try and uaing earlier version?

**Comment by tabernarious** [comment]
I just figured out the issue and am releasing v3.1.9 momentarily. Sorry for the trouble. I must not have tested after I added a last-minute comment within one script.

**Comment by tabernarious** [comment]
v3.1.9 is out and should fix this! Please test and confirm then I'll close this issue.

**Comment by matantal1** [comment]
Thanks Daniel!
I'll try and update.

**Comment by matantal1** [comment]
@tabernarious 
Works like a charm!
Thanks for the fast fix. Appreciate your effort !
