### ISSUE TITLE
mount.cifs has wrong syntax

### ISSUE THREAD

**Issue by domingo13** [tabernarious/f5-automated-backup-iapp#20]
I can see that the mount command is in the format:
mount -t cifs //\${server}/\${msshare}\${mssubdir} \${mountp} -o user=\${username}%\'\'\${password}\'\',domain=\${msdomain}

This doesn't work for me to mount my Synology NAS, so I changed it to this:

mount -t cifs //\${server}/\${msshare}\${mssubdir} \${mountp} -o user=\${username},password=\${password},domain=\${msdomain}

And then it works :-)

I haven't tried it out on a Windows environment.
I'm running version 14.1.0.2

**Comment by jokragly** [comment]
I am having the same issue sending to a windows share and the syntax correction did not fix it, actually the script stops after it saves it local.  Would love to see some type of fix for this.  I have also done the ssh/sftp to my NAS and it fails with to many invalid login attempts.

**Comment by tabernarious** [comment]
`mount` options formatting has been updated and expanded in iApp v13.1.10, which should address this issue.
