### ISSUE TITLE
change UCS default directory

### ISSUE THREAD

**Issue by stefan-engel** [tabernarious/f5-automated-backup-iapp#21]
Due to limited disk space on /var/local, I 've tired to manually change it withing the iAPP template:
f5.automated_backup.v3.1.9
set backup_directory /shared/tmp/ucs
It looks fine, from log (exec logger -p local0.info "f5.automated_backup iApp ALVA-F501_BKP: $fname_log SAVED LOCALLY (/shared/tmp/ucs)"), but nothing gets created in /shared/tmp/ucs.

Any chance this can be changed or added as a feature in an upcoming version?

**Comment by tabernarious** [comment]
I realize this is a very old request, but this will be available in v3.2.4!

**Comment by tabernarious** [comment]
This has been fixed in v3.2.4, which I released today. Reopen this issue if you have further issues or requests.
