### ISSUE TITLE
Cannot copy to remote SCP site with v3.1.9

### ISSUE THREAD

**Issue by rpasche** [tabernarious/f5-automated-backup-iapp#23]
Trying to backup the files to a remote SCP server with version 3.1.9 on a F5 v 14.1 fails.

I found out that it looks like the whole key is not stored. The input is truncated after the first newline, so it just stores the header "-----BEGIN RSA PRIVATE KEY-----" and that's it.

I'm wondering, what "string" should be put into the private ssh key field.

I fixed my version of the template by replacing all '\n' chars with '|' prior to pasting the key into the ssh key field and just revert this change while decrypting the key later.

What format on the private SSH key am I missing that seems to work everywhere?

rpasche

**Comment by tabernarious** [comment]
Interesting. Pasting the private key is definitely finnicky. I would make sure you are PEM format with Unix-style end-of-line (LF, not CRLF). If you're working in Windows make sure you paste the key into an editor like Notepad++ first and set the EOL format to LF.

**Comment by rpasche** [comment]
Hm....this is pretty old. Didn't know, that this is still open and I do not have access to my changes because those were done at customer site, where I am not anymore.

**Comment by tabernarious** [comment]
I know it's been a while. Trying to brush it up and tie up any loose ends still out there. I'll close this issue for now.
