### ISSUE TITLE
Backup Passphrase with $ causes failure

### ISSUE THREAD

**Issue by sbbowman** [tabernarious/f5-automated-backup-iapp#26]
When using a backup passphrase that includes a $, the backup fails and this error is logged in ltm.log:

Feb  7 02:14:01 <hostname> err scriptd[27373]: 014f0013:3: Script (/Common/f5.automated_backup__backup-test) generated this Tcl error: (script did not successfully complete: (can't read "<text after the $>": no such variable

Looks like the $ isn't being escaped in the passphrase.

**Comment by tabernarious** [comment]
If this is still an issue, or you remember, which version of the iApp are/were you using?

**Comment by sbbowman** [comment]
Still running the affected version - 3.1.9.  Should I try a newer one?

**Comment by tabernarious** [comment]
I think I misunderstood this. You’re talking about the passphrase used to encrypt the UCS?

**Comment by sbbowman** [comment]
Correct.

**Comment by tabernarious** [comment]
3.1.10 did not have any fixes related to this issue, but I’ll take a look.

**Comment by tabernarious** [comment]
This should be fixed in v3.1.11 and v3.2.1. I also added notes in the iApp regarding some specific special characters that will not work. Please try v3.2.1 and let me know!
