### ISSUE TITLE
F5 version 15 - the login / password parse is not correct.

### ISSUE THREAD

**Issue by mcamagco** [tabernarious/f5-automated-backup-iapp#30]
Hello all
We use the 3.1.9 version of that application to place the backup in a windows folder.
We upgraded the F5 to 15v that has a new features that we need in our company. However, with the new version the iapp doesn't work. As the F5 error it looks like a issue in the parse with the login / password.

"
Password entry required for 'Password for login%password@//dyrag.domain.com/weekday/F5/bck/:' (PID 14241).
Please enter password with the systemd-tty-ask-password-agent tool!
"
Note: We tested with several login and password and the result is the same.

Anyone has the same issue ? How you solved ?
There are a new iapp version incoming to solved the issue ?

Thank you all

**Comment by ChrisL16** [comment]
Hello @mcamagco
You can try to replace 

user=\${username}%\'\'\${password}\'\',domain=\${msdomain}

with 

user=\${username},password=\'\'\${password}\'\',domain=\${msdomain},sec=ntlmsspi

in line 336. This works fine for me.

**Comment by tabernarious** [comment]
@chrislan16 , What version are you running? I'll test this--sounds promising :)

**Comment by ChrisL16** [comment]
Sorry, I forogot to mention. I am running it with V14 and V15.

**Comment by tabernarious** [comment]
As of iApp v3.1.10, SMB/CIFS should now be supported on v14+. Please test and report back.

**Comment by ChrisL16** [comment]
I have tested successfully in V14 and V15. Thank you for the update!
