### ISSUE TITLE
where does the scripts.sh file go?

### ISSUE THREAD

**Issue by scratchfury** [tabernarious/f5-automated-backup-iapp#33]
I feel like a dummy, but I can't figure out where f5.automated_backup.vx.x.x.scripts.sh goes.  Where does it go?

**Comment by tabernarious** [comment]
No worries. No need to install the script anywhere. The script file is just a reference for what is integrated into the iApp template. In the iApp the scripts are stripped down to one line (\n for new lines, \t for tabs) which makes them REALLY hard to read and work with when developing or debugging.
