### ISSUE TITLE
SFTP failing with CHILDSTATUS 21707 1 and REMOTE COPY (SFTP) STARTING sftp: illegal option -- i

### ISSUE THREAD

**Issue by cbrandys** [tabernarious/f5-automated-backup-iapp#35]
When I try to back up my LTM's with SFTP I receive the illegal option error as well as the childstatus error. I have confirmed that I am able to SFTP from the F5 to SFTP server via cli so the private key and known_hosts should not be a problem. I also have tried with SCP and same errors.

Here is the output. 

Saving active configuration...
s_F5_Backup: STARTED
f5.automated_backup iApp site01_F5_Backup: ltm01.example.com_20210628162020.ucs GENERATING

/var/local/ucs/ltm01.example.com_20210628162020.ucs is saved.
f5.automated_backup iApp site01_F5_Backup: ltm01.example.com_20210628162020.ucs SAVED LOCALLY (/var/local/ucs)
f5.automated_backup iApp site01_F5_Backup: ltm01.example.com_20210628162020.ucs REMOTE COPY (SFTP) STARTING
sftp: illegal option -- i
usage: sftp [-1Cv] [-B buffer_size] [-b batchfile] [-F ssh_config]
            [-o ssh_option] [-P sftp_server_path] [-R num_requests]
            [-S program] [-s subsystem | sftp_server] host
       sftp [[user@]host[:file [file]]]
       sftp [[user@]host[:dir[/]]]
       sftp -b batchfile [user@]host
f5.automated_backup iApp site01_F5_Backup: ltm01.example.com_20210628162020.ucs REMOTE COPY (SFTP) FAILED ErrorCode: CHILDSTATUS 20317 1
f5.automated_backup iApp site01_F5_Backup: ltm01.example.com_20210628162020.ucs REMOTE COPY (SFTP) FAILED ErrorInfo: child process exited abnormally
    while executing
"exec $scriptfile"
f5.automated_backup iApp site01_F5_Backup: ltm01.example.com_20210628162020.ucs REMOTE COPY (SFTP) FAILED (check for errors above)
f5.automated_backup iApp site01_F5_Backup: FINISHED

**Comment by tabernarious** [comment]
What version of F5 TMOS are you using? And what version of this iApp template? I haven't run into the "sftp: illegal option -- i" before.

**Comment by tabernarious** [comment]
@cbrandys ,  Closing due to no follow-up. Please reopen if you are still having issues.
