### ISSUE TITLE
"Use SSH key created by F5" + "Suggest using ssh-copy-id" 

### ISSUE THREAD

**Issue by tristanbob** [tabernarious/f5-automated-backup-iapp#5]
Would it be a good idea to use the SSH keys created by F5?  Does this key stay static? Is it included in UCS backups?

`/root/.ssh/identity -> /var/ssh/root/identity`

Also, perhaps  you should suggest using "ssh-copy-id" as a simple way to get the public key to the backup server:

`ssh-copy-id -i /var/ssh/root/identity.pub -o Ciphers=aes256-ctr myusername@mybackupserver`

**Comment by tristanbob** [comment]
I just realized that using the default F5 keys will only work for stand-alone systems.  This is because the iapp config is synced between all devices in a sync group.   This config includes the private key that the iapp will use, so you need to make sure the same key is present on all devices in the sync group.

I don't think there is a good way to support using multiple keys in the iapp, but I could be wrong.  You could do this:
"Try Key#1, if failed authentication, Try #2."  
That could work, but it's not elegant and would fill the logs with failed logins.

**Comment by tabernarious** [comment]
@tristanbob I have added your ssh-copy-id suggestion in the "Copy/Paste the SSH private key" help sections (iApp v3.1.2).

I am going to leave the keys alone for now. As you suggest, this may make it messier; I would like to keep it simple and clean for now.
