### ISSUE TITLE
SMB:: Unable to find suitable address

### ISSUE THREAD

**Issue by limyj90** [tabernarious/f5-automated-backup-iapp#8]
When using SMB/CIFS on version 12.1.3, received following error.

Unable to find suitable address.

**Comment by tabernarious** [comment]
I'll have to test this and see what's up.

**Comment by limyj90** [comment]
Hi, thanks for replying this. I am able to figure out the issue is with the source IP used by SMB is not being allowed at firewall. 

I am thinking if that is possible to add an option to specify source IP/interface being used, so it would ease the team to open up firewall for external F5 appliance behind firewall.

**Comment by tabernarious** [comment]
@limyj90 Explicitly setting the source IP (or interface) may be difficult, especially in HA configurations. In iApp v3.1.2 I added a Source IP information section (no settings) with this information:

"Connections to the Destination will be sourced from a non-floating Self IP or from the Management IP based on L2/L3 networking. If the Destination is in the same subnet as a Self IP or the Management IP, you cannot easily affect the source IP. If the Destination must be routed, you can manipulate the source IP by creating a TMM route or Management Route to force the L3 next-hop/gateway (the BIG-IP will use a source IP in the same subnet as the L3 next-hop/gateway)."

Is this helpful?
